spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oos?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: atree
    password: 12345678
    
    
mybatis:
  config-location: classpath:mybatis-config.xml 
  
  mapper-locations: classpath:/mapper/*.xml
  

    
